spring:
  application:
    name: data-visualizer
  datasource:
    url: jdbc:postgresql://localhost:5432/data-visualizer
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgresPlusDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

file:
  upload-dir: ./data/uploads # Where files are stored