name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datavisualizer-artifacts
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: datavisualizer-artifacts

      # Example deployment step (replace with your actual deployment logic)
      - name: Deploy to Server (placeholder)
        run: echo "Deploying application..."
        # Add your deployment commands here, e.g., scp, rsync, kubectl, etc.