name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4

      - name: Clone frontend repository
        run: |
          git clone https://github.com/your-org/your-frontend-repo.git frontend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          npm run dev

      - name: Archive frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build

  build:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4

      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -DskipTests clean install

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datavisualizer-artifacts
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: datavisualizer-artifacts

      # Example deployment step (replace with your actual deployment logic)
      - name: Deploy to Server (placeholder)
        run: echo "Deploying application..."
        # Add your deployment commands here, e.g., scp, rsync, kubectl, etc.